# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  solutionFile: 'DDRScoreTracker.API.sln'

steps:
- script: dotnet restore $(solutionFile)
  displayName: 'dotnet restore'
- script: dotnet build $(solutionFile) --no-restore --configuration $(buildConfiguration)
  displayName: 'dotnet build'
- script: dotnet test $(solutionFile) --no-restore --no-build --configuration $(buildConfiguration)
  displayName: 'dotnet test'
- task: Docker@2
  displayName: 'Log into Docker Hub'
  inputs:
    command: login
    containerRegistery: DockerHub
- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    command: buildAndPush
    repository: ddr-score-tracker
    dockerfile: DDRScoreTracker.API/Dockerfile.ci
    tags: |
      $(Build.BuildId)
      latest