# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  solutionFile: 'DDRScoreTracker.API.sln'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore Packages'
  inputs:
    command: restore
    projects: $(solutionFile)
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: build
    projects: $(solutionFile)
    arguments: --configuration $(buildConfiguration)
- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: test
    projects: $(solutionFile)
    arguments: --no-build --configuration $(buildConfiguration)
- task: Docker@2
  displayName: 'Log into Docker Hub'
  inputs:
    command: login
    containerRegistry: DockerHub
- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    command: buildAndPush
    repository: duraz0rz/ddr-score-tracker
    dockerfile: DDRScoreTracker.API/Dockerfile.ci
    tags: |
      $(Build.SourceBranchName)-api-$(Build.BuildNumber)
      $(Build.SourceBranchName)-api-latest
